name: sharing_session
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.1.0+1
  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter_bloc: ^7.2.1
  flutter_html: ^2.1.5 # Html Decoder to Text widget library
  flutter_secure_storage: "5.0.2"
  #  flutter_svg: ^0.23.0+1
  fluttertoast: ^8.0.8
  formz: ^0.4.1


  http: ^0.13.5
  image_picker: ^0.8.6
  json_annotation: ^4.3.0   # Annotation for json serialization and deserialization
  #  requires SDK version >=2.17.1 <3.0.0
  #  pdfx: ^2.2.0  # PDF viewer and renderer using native API
  path_provider: ^2.0.11
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.5   # A runner to generate a code from a class manually or by watching for file changes
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1   # Utility to auto generate from and to json function

  # Integration Test
  integration_test:
    sdk: flutter

  # Unit Testing
  bloc_test: ^8.1.0
  mockito: ^5.0.15
  mocktail: ^0.1.4
  
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/