// Mocks generated by Mockito 5.4.0 from annotations
// in sharing_session/test/mock/repositories/repositories.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sharing_session/api/api.dart' as _i2;
import 'package:sharing_session/models/models.dart' as _i3;
import 'package:sharing_session/repositories/comment_repository.dart' as _i4;
import 'package:sharing_session/repositories/post_repository.dart' as _i6;
import 'package:sharing_session/repositories/user_repository.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCommentsApi_0 extends _i1.SmartFake implements _i2.CommentsApi {
  _FakeCommentsApi_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostsApi_1 extends _i1.SmartFake implements _i2.PostsApi {
  _FakePostsApi_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePosts_2 extends _i1.SmartFake implements _i3.Posts {
  _FakePosts_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUsersApi_3 extends _i1.SmartFake implements _i2.UsersApi {
  _FakeUsersApi_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUsers_4 extends _i1.SmartFake implements _i3.Users {
  _FakeUsers_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CommentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommentRepository extends _i1.Mock implements _i4.CommentRepository {
  MockCommentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CommentsApi get commentsApi => (super.noSuchMethod(
        Invocation.getter(#commentsApi),
        returnValue: _FakeCommentsApi_0(
          this,
          Invocation.getter(#commentsApi),
        ),
      ) as _i2.CommentsApi);
  @override
  _i5.Future<List<_i3.Comments>> getListComments({String? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListComments,
          [],
          {#id: id},
        ),
        returnValue: _i5.Future<List<_i3.Comments>>.value(<_i3.Comments>[]),
      ) as _i5.Future<List<_i3.Comments>>);
}

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i6.PostRepository {
  MockPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PostsApi get postsApi => (super.noSuchMethod(
        Invocation.getter(#postsApi),
        returnValue: _FakePostsApi_1(
          this,
          Invocation.getter(#postsApi),
        ),
      ) as _i2.PostsApi);
  @override
  _i5.Future<List<_i3.Posts>> getListPosts() => (super.noSuchMethod(
        Invocation.method(
          #getListPosts,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Posts>>.value(<_i3.Posts>[]),
      ) as _i5.Future<List<_i3.Posts>>);
  @override
  _i5.Future<_i3.Posts> getPostById({String? id}) => (super.noSuchMethod(
        Invocation.method(
          #getPostById,
          [],
          {#id: id},
        ),
        returnValue: _i5.Future<_i3.Posts>.value(_FakePosts_2(
          this,
          Invocation.method(
            #getPostById,
            [],
            {#id: id},
          ),
        )),
      ) as _i5.Future<_i3.Posts>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i7.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UsersApi get usersApi => (super.noSuchMethod(
        Invocation.getter(#usersApi),
        returnValue: _FakeUsersApi_3(
          this,
          Invocation.getter(#usersApi),
        ),
      ) as _i2.UsersApi);
  @override
  _i5.Future<_i3.Users> getUsers() => (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
        ),
        returnValue: _i5.Future<_i3.Users>.value(_FakeUsers_4(
          this,
          Invocation.method(
            #getUsers,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Users>);
}
